{% set name = "gempy" %}
{% set version = "2.2.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 57a996bd8a9ad013537f9db8dac26deeee0e1929494a4714b87ce154eed61ab1

build:
  noarch: python
  number: 2
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - pandas <=1.0.5
    - matplotlib-base
    - numpy
    - networkx
    - pyvista
    - scikit-image >=0.17
    - seaborn >=0.9
    - theano >=1.0.4
    - pymc3
    - ipython
    - pytest

test:
  imports:
    - gempy

about:
  home: https://github.com/cgre-aachen/gempy
  license: LGPL-3.0-only
  license_file: LICENSE
  license_family: LGPL
  summary: Open-source, implicit 3D structural geological modeling in Python for uncertainty analysis

  description: |
    GemPy is an open-source, Python-based 3-D structural geological modeling software,
    which allows the implicit (i.e. automatic) creation of complex geological models
    from interface and orientation data. It also offers support for stochastic modeling
    to adress parameter and model uncertainties
  doc_url: https://docs.gempy.org/
  dev_url: https://github.com/cgre-aachen/gempy

extra:
  recipe-maintainers:
    - Leguark
    - AndrewAnnex
