{% set name = "gempy" %}
{% set version = "2025.1.0" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/gempy-{{ version }}.tar.gz
  sha256: 3b9e9d3ce9a94694116592e1f7327440c8f077862e0e18ad1102b3e9c4ea1fc6

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
    - setuptools-scm
  run:
    - python >={{ python_min }}
    - gempy-engine >=2025.1.1,<2026.0.0.dev
    - typing_extensions


test:
  requires:
    - python {{ python_min }}
    - pip
  imports:
    - gempy
  commands:
    - pip check

about:
  home: https://github.com/gempy-project/gempy
  license: EUPL-1.2
  license_file: LICENSE
  summary: Open-source, implicit 3D structural geological modeling in Python for uncertainty analysis

  description: |
    GemPy is an open-source, Python-based 3-D structural geological modeling software,
    which allows the implicit (i.e. automatic) creation of complex geological models
    from interface and orientation data. It also offers support for stochastic modeling
    to adress parameter and model uncertainties
  doc_url: https://docs.gempy.org/
  dev_url: https://github.com/gempy-project/gempy

extra:
  recipe-maintainers:
    - sebhmg
    - conda-forge/geoh5py
    - Leguark
    - AndrewAnnex
