{% set name = "gempy" %}
{% set version = "2024.2.0.2" %}
{% set python_min = "3.10" %}
{% set python_max = "3.12" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/gempy-{{ version }}.tar.gz
  sha256: e01abba7026078234b3cecd6102257cb4dd6e3426614728c70deaa7be48f8533

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
    - setuptools-scm
  run:
    - python >={{ python_min }},<{{ python_max }}
    - gempy-engine >=2024.2.0,<2024.3.dev0


test:
  requires:
    - python {{ python_min }}
    - pip
  imports:
    - gempy
  commands:
    - pip check

about:
  home: https://github.com/gempy-project/gempy
  license: LGPL-3.0-only
  license_file: LICENSE
  license_family: LGPL
  summary: Open-source, implicit 3D structural geological modeling in Python for uncertainty analysis

  description: |
    GemPy is an open-source, Python-based 3-D structural geological modeling software,
    which allows the implicit (i.e. automatic) creation of complex geological models
    from interface and orientation data. It also offers support for stochastic modeling
    to adress parameter and model uncertainties
  doc_url: https://docs.gempy.org/
  dev_url: https://github.com/gempy-project/gempy

extra:
  recipe-maintainers:
    - SophieCurinier
    - Leguark
    - AndrewAnnex
